close all
figure(1)
set(1,'Position',[2700, 200, 900 1330])
newNames = dat.results.breedname;

subplot(4,4,1)
ix = dat.results.meanIndiv;
hold on
plot([1 1],[mean(ix)-std(ix)./sqrt(length(ix)) mean(ix)+std(ix)./sqrt(length(ix))],'k')
plot(1,mean(ix),'.','MarkerFaceColor','k','MarkerEdgeColor','k','MarkerSize',12)
plot([.5 1.5],[.5 .5],'k--')
ylabel('Proportion correct') 
set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'XTick'       , [ ], ...
  'XTickLabel'  , {''},...
  'YTick'       , [0:.25:1], ...
  'XColor'      , [0 0 0], ...
  'YColor'      , [0 0 0], ...
   'LineWidth'   , 1         );
axis([0.5 1.5 0 1])
text(.25, 1.1, 'A','Fontsize',16)

subplot(4,4,2:4)
hold on
cx = 1;
TX = dat.results.meanIndivBreed;
for i = 1:length(TX)
    plot([cx cx],[mean(TX{i})-std(TX{i})./sqrt(length(TX{i})) mean(TX{i})+std(TX{i})./sqrt(length(TX{i}))],'k')
    plot(cx,mean(TX{i}),'.','MarkerFaceColor','k','MarkerEdgeColor','k','MarkerSize',12)
    cx = cx + 1;
end
plot([.5 length(TX)+.5],[.5 .5],'k--')
xlabel('Dog breed')   
set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.0075 .0075] , ...
  'XMinorTick'  , 'off'      , ...
  'YMinorTick'  , 'on'      , ...
  'XTick'       , [1:length(TX)], ...
  'XTickLabel'  , newNames,...
  'YTick'       , [0:.25:1], ...
  'XColor'      , [0 0 0], ...
  'YColor'      , [0 0 0], ...
   'LineWidth'   , 1         );
axis([0.5 length(TX)+.5 0 1])
text(-.05, 1.1, 'B','Fontsize',16)

subplot(4,4,5)
cx = [-.15 0 .15];
jx = dat.results.meanIndivCondition;
hold on
plot([.5 1.5],[.5 .5],'k--')
for i = 1:size(jx,1)
    plot([1+cx(i) 1+cx(i)],[mean(jx(i,:))-std(jx(i,:))./sqrt(length(jx(i,:))) mean(jx(i,:))+std(jx(i,:))./sqrt(length(jx(i,:)))],'k')
    plot(1+cx(i),mean(jx(i,:)),'.','MarkerFaceColor','k','MarkerEdgeColor','k','MarkerSize',12)
end
ylabel('Proportion correct')  
set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'XTick'       , [ ], ...
  'XTickLabel'  , {''},...
  'YTick'       , [0:.25:1], ...
  'XColor'      , [0 0 0], ...
  'YColor'      , [0 0 0], ...
   'LineWidth'   , 1         );
axis([0.5 1.5 0 1])
text(.25, 1.1, 'C','Fontsize',16)

subplot(4,4,[2:4]+4)
hold on
cx = [-.15 0 .15];
PX = dat.results.meanIndivBreedCondition;
for i = 1:size(PX,2)
    for j = 1:size(PX,1)
        plot([i+cx(j) i+cx(j)],[mean(PX{j,i})-std(PX{j,i})./sqrt(size(PX{j,i},2)) mean(PX{j,i})+std(PX{j,i})./sqrt(size(PX{j,i},2))],'k')
        plot(i+cx(j),mean(PX{j,i}),'.','MarkerFaceColor','k','MarkerEdgeColor','k','MarkerSize',12)
    end
end
plot([.5 length(PX)+.5],[.5 .5],'k--')
xlabel('Dog breed')
set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.0075 .0075] , ...
  'XMinorTick'  , 'off'      , ...
  'YMinorTick'  , 'on'      , ...
  'XTick'       , [1:length(PX)], ...
  'XTickLabel'  , newNames,...
  'YTick'       , [0:.25:1], ...
  'XColor'      , [0 0 0], ...
  'YColor'      , [0 0 0], ...
   'LineWidth'   , 1         );
axis([0.5 length(PX)+.5 0 1])
text(-.05, 1.1, 'D','Fontsize',16)